#
# development configuration
#
spring:
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 100MB
   devtools:
      livereload:
         enabled: true
server:
   port: 0
   servlet:
      context-path: /
      encoding:
         charset: UTF-8
         enabled: true
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
storage:
   location: E:/service-storage/assets
   httpd:
      host: localhost
      port: 9999
logging:
   pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   level:
      root: INFO   